// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPredictions(arg1:string):Promise<void>;

export function InitCandles(arg1:string):Promise<string>;
